services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    networks:
      - surikat-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./portainer_key.txt:/run/secrets/portainer:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer_web.rule=Host(`portainer.surikat.io`)"
      - "traefik.http.routers.portainer_web.entrypoints=websecure,web"
      - "traefik.http.routers.portainer_web.tls=true"
      - "traefik.http.services.portainer_web.loadbalancer.server.port=9443"

volumes:
  portainer_data:
    name: portainer_data

networks:
  surikat-network:
    external: true
